[project]
name = "xray"
version = "0.1.0"
description = "XRAY: Fast code intelligence for AI assistants"
dependencies = [
    "fastmcp>=0.1.0",
    "tree-sitter>=0.20.0",
    "tree-sitter-python>=0.20.0",
    "tree-sitter-javascript>=0.20.0", 
    "tree-sitter-typescript>=0.20.0",
    "tree-sitter-go>=0.20.0",
    "pydantic>=2.0.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
xray-mcp = "xray.mcp_server:main"