name: Auto Publish on Main

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Bump version and create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false

      - name: Install uv
        if: steps.tag_version.outputs.new_tag
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        if: steps.tag_version.outputs.new_tag
        run: uv python install

      - name: Build package
        if: steps.tag_version.outputs.new_tag
        run: uv build

      - name: Publish to GitHub Packages
        if: steps.tag_version.outputs.new_tag
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: uv publish
