name: Publish to GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for hatch-vcs versioning

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Build package
        run: uv build

      - name: Publish to GitHub Packages
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UV_PUBLISH_URL: https://pypi.pkg.github.com/Jamie-BitFlight
        run: uv publish
